config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    # post '/topics/guest_sign_in', to: 'topics#guest_sign_in'

  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'tops#index'

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  resources :users do
    member do
      get :following, :followers
    end
  end  

  resources :topics do
    resources :comments
      collection do
        get 'search'
      end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 300}
  mount_uploader :image, ImageUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :index]
  
  def index
    @topics = Topic.all.order(created_at: :desc)
    @q = @topics.ransack(params[:q])
    @topics = @q.result(distinct: true)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      redirect_to topics_path, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @favorite = current_user.favorites.find_by(topic_id: @topic.id)
    @comments = @topic.comments
    @comment = @topic.comments.build
  end

  def edit
    redirect_to topics_path, notice: "不正操作を記録しました。" unless current_user.id == @topic.user.id
  end

  def update
    if @topic.update(topic_params)
      redirect_to topics_path, notice: '編集しました'
    else
      render :new
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: '削除しました'
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
    sign_in user
    redirect_to topics_path, notice: 'ゲストユーザーとしてログインしました。'
  end


  private

  def topic_params
    params.require(:topic).permit(:title, :content, :image, :image_cache, :user_id)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def check_sender
    redirect_to topics_path, alert: ‘アクセス権限がありません’ if @topic.user_id != current_user.id
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
  <ul>
    <% @topic.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model:@topic, local: true) do |form| %>
  <div>
    <%= form.label :title, 'タイトル' %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content, 'コンテンツ' %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.label :image, '画像' %>
    <%= image_tag(@topic.image.url) if @topic.image && @topic.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div>
    <%= form.submit '更新' %>
  </div>
<% end %>
<%= link_to '一覧に戻る', topics_path %> 

app/views/topics/create.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/edit.html.erb
<%= render'application/sidebar' %>
<h3>Topic編集</h3>
<%= render 'form' %>

app/views/topics/index.html.erb
<%= render'application/sidebar' %>
<div class = "topic_all">
<div class = "topic_index">
  <h1 class = "title_tops">Topics</h1>
<% if current_user.try(:admin?) %>
  <h3><%= link_to "管理者画面へ", rails_admin_path %></h3>
<% end %>

<%= search_form_for @q do |f| %><br>
  <%= f.label :title_cont, 'タイトルor内容検索' %>
  <%= f.search_field :title_or_content_cont ,placeholder:"タイトルor内容"%>
  <%= f.submit '検索' %>
<% end %>
</div>
<table class="topic_content">
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>image</th>
  </tr>
  <% @topics.each do |topic| %>
  <tr class="topics-index_row" id=<%= "topics-index_row-#{topic.id}" %>>
    <td id=<%= "topics-index_row-#{topic.id}_title" %>><%= topic.title %></td>
    <td id=<%= "topics-index_row-#{topic.id}_content" %>><%= topic.content %></td>
    <td id=<%= "topics-index_row-#{topic.id}_image" %>><%= image_tag(topic.image.url) if topic.image && topic.image.url %></td>
    <td><%= link_to '詳細', topic_path(topic.id), id: "topics-index_row-#{topic.id}_show", class: 'btn btn-primary' %></td>
    <% if current_user.id == topic.user.id %>
      <td><%= link_to '編集', edit_topic_path(topic.id), id: "topics-index_row-#{topic.id}_edit", class: 'btn btn-primary' %></td>
      <td><%= link_to '削除', topic_path(topic.id), method: :delete, data: {confirm: '削除してよろしいですか？'}, id: "topics-index_row-#{topic.id}_destroy", class: 'btn btn-danger' %></td>
    <% end %>
    <td><% if user_signed_in? %>
      <% unless topic.user_id == current_user.id %>
        <% if current_user.favorites.find_by(topic_id: topic.id).present? %>
          <%= link_to 'お気に入り解除する', favorite_path(id: current_user.favorites.find_by(topic_id: topic.id).id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'お気に入りする', favorites_path(topic_id: topic.id), method: :topic, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    <% end %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/topics/new.html.erb
<%= render'application/sidebar' %>
<h3>Topic作成</h3>
<% if @topic.errors.any? %>
  <ul>
    <% @topic.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model:@topic, local: true) do |form| %>
  <div>
    <%= form.label :title, 'タイトル' %>
    <%= form.text_field :title, placeholder:"タイトルを入力" %>
  </div>
  <div>
    <%= form.label :content, 'コンテンツ' %>
    <%= form.text_field :content, placeholder:"コンテンツを入力" %>
  </div>
  <div>
    <%= form.label :image, '画像' %>
    <%= image_tag(@topic.image.url) if @topic.image && @topic.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div>
    <%= form.submit '投稿' %>
  </div>
<% end %>
<%= link_to '一覧に戻る', topics_path %> 

app/views/topics/show.html.erb
<%= render'application/sidebar' %>
<div class="topic_show content">

<h3>Topic詳細</h3>
<div class = "topic_content">
<p><%= image_tag (@topic.image.url)if @topic.image && @topic.image.url %></p>  
<% if current_user.id == @topic.user.id %>
    <%= link_to '編集', edit_topic_path(@topic) %>
  <% end %>
  <div class = "topic_inner">
    <p>投稿者:<%=link_to "#{@topic.user.name}", user_path(@topic.user.id) %></p>
    <p>タイトル：<%= @topic.title %></p>
    <p>内容：<%= @topic.content %></p>
    <% unless @topic.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(topic_id: @topic.id), method: :topic, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="topic-text">
  </div>
  <p>コメント一覧</p>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
  </div>
  <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
  </div>
<%= link_to '一覧に戻る', topics_path %> 
</div>