config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
    # post '/topics/guest_sign_in', to: 'topics#guest_sign_in'

  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'tops#index'

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  resources :users do
    member do
      get :following, :followers
    end
  end  

  resources :topics do
    resources :comments
      collection do
        get 'search'
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_item(name, path)
    class_name = 'channel'
    class_name << ' active' if current_page?(path)
    content_tag :li, class:class_name do
      link_to name, path, class: 'channel_name'
    end
  end
end

app/views/application/_sidebar.html.erb
<div class="listings">
  <div class="listings_channels">
    <h4>Menu</h4>
    <ul class="channel_list">
      <br>
      <br>
        <li><%= sidebar_link_item('Topic一覧', topics_path) %></li>
      <br>
      <br>
        <li><%= sidebar_link_item('新規投稿', new_topic_path) %></li>
      <br>
      <br>
        <li><%= sidebar_link_item('お気に入り一覧', favorites_path) %></li>
      <br>
      <br>
        <li><%= sidebar_link_item('Myプロフィール', user_path(current_user.id)) %></li>
      <br>
      <br>
    </ul>
  </div>
</div> 